In [9]:
import pandas as pd
import sys

print(sys.executable)

/home/nvisscher/venvs/social-media-data-map/bin/python

In [10]:
root = '/projects/prjs2007/survey_data/'

df_nl = f'{root}survey_data_netherlands/DUVATK25_W1_W2_eindbestand_excl_jamboid_en_koppelnummer_17122025.sav'
df_es = f'{root}survey_data_spain/VUAMNL_282481_w1_20251121.xlsx'

df_nl = pd.read_spss(df_nl)
df_es = pd.read_excel(df_es)

In [11]:
df_nl.head()

,W1_Toestemmingsverklaring,W1_Q1_1_1,W1_Q1_1_2,W1_Q1_1_3,W1_Q1_1_4,W1_Q1_1_5,W1_Q1_7_1,W1_Q1_7_2,W1_Q1_7_3,W1_Q1_7_4,...,NIELSEN4,IOPOL2023,LEEFTIJD,HUISHOUDENSSAMENSTELLING,IOWERKSIT,IOINKOMEN_NEW,ETNICITEIT_CBS1STEEKPROEF,ETNICITEIT_CBS2STEEKPROEF,POSTCODE_NUMMER,koppelnummer
0,Ja_ik_doe_mee,Ongeveer één keer per dag,Ongeveer één keer per dag,Ongeveer één keer per dag,Ongeveer één keer per dag,Nooit,"Noch mee eens, noch mee oneens",Een beetje oneens,Een beetje oneens,Sterk mee oneens,...,Noord,GroenLinks-PvdA,80.0,"ik woon samen met partner, zonder thuiswonende...",gepensioneerd of VUT,tussen 1 en 2 keer modaal (€49.500 tot€83.000),Nederland,Nederlands,7957.0,1.0
1,Ja_ik_doe_mee,Nooit,Minder dan één keer per week,Nooit,Minder dan één keer per week,Ongeveer één keer per week,Sterk mee eens,Enigszins mee eens,Sterk mee eens,Sterk mee eens,...,West,GroenLinks-PvdA,26.0,"ik woon samen met partner, zonder thuiswonende...","werkzaam bij de semi-overheid (onderwijs, zorg...",modaal (€41.500 tot€49.500),Nederland,Nederlands,3543.0,2.0
2,Ja_ik_doe_mee,Meerdere keren per week,Meerdere keren per week,Ongeveer één keer per dag,Meerdere keren per week,Meerdere keren per week,Een beetje mee eens,"Noch mee eens, noch mee oneens",Een beetje mee eens,Een beetje mee eens,...,Oost,VVD,78.0,"ik woon samen met partner, zonder thuiswonende...",gepensioneerd of VUT,bijna modaal (€33.500 tot€41.500),Nederland,Nederlands,7641.0,3.0
3,Ja_ik_doe_mee,Meerdere keren per week,Ongeveer één keer per dag,Ongeveer één keer per week,Meerdere keren per dag,Meerdere keren per dag,Een beetje oneens,Enigszins mee eens,Sterk mee eens,Enigszins mee eens,...,West,D66,30.0,"ik woon samen met partner, zonder thuiswonende...",werkzaam in loondienst (bedrijfsleven),modaal (€41.500 tot€49.500),Nederland,Nederlands,3522.0,4.0
4,Ja_ik_doe_mee,Meerdere keren per dag,Meerdere keren per week,Meerdere keren per week,Meerdere keren per dag,Ongeveer één keer per dag,Een beetje mee eens,Een beetje mee eens,Een beetje mee eens,Enigszins oneens,...,West,NSC,52.0,"ik woon samen met partner, met thuiswonende ki...",werkzaam bij de overheid,meer dan 2 keer modaal (€99.000 of meer),Nederland,Nederlands,2552.0,5.0

In [12]:
df_es.head()

,key,numericalId,accessCount,startTime,endTime,duration,status,type,ppi_tp,CodPanelista,...,QJ1_10,INTERVENTION,INT1,NEWS_SELECTION,DECLARACION,QP6#1,QP6#2,QP6#3,FASES,CAMBIO_20251114
0,09c39a8b-b541-4824-aaa6-d7398e4a0347,693448528,1,2025-11-18 15:45:29,2025-11-18 15:59:55,865.0,end,complete,co_1,0017a3da81690a8d,...,6,4,1.0,2.0,NaN,NaN,NaN,NaN,1,1.0
1,a6ff7ca4-f33a-4bd6-8a73-9be89713377f,692988992,1,2025-11-17 08:50:25,2025-11-17 09:03:16,771.0,end,complete,co_0,00241a5156cc9c41,...,2,1,NaN,NaN,1.0,1.0,0.0,0.0,3,1.0
2,f5836f97-4899-48f1-a7d6-c32bc425ae1f,692459383,1,2025-11-14 10:18:17,2025-11-14 10:49:13,1855.0,end,complete,co_1,00658962ac3045d7,...,6,1,NaN,NaN,1.0,0.0,0.0,1.0,1,NaN
3,46c3da14-5e2d-4702-8808-451d8c0bb652,693001097,1,2025-11-17 10:53:28,2025-11-17 11:28:52,2123.0,end,complete,co_0,0065bff0b4580b30,...,5,2,1.0,NaN,1.0,1.0,0.0,0.0,3,1.0
4,2029f15f-b9f0-4fee-ab71-a016a7b29eb5,693011641,3,2025-11-17 12:07:01,2025-11-17 12:42:19,2127.0,end,complete,co_1,00b572d1500a325f,...,7,2,1.0,NaN,1.0,0.0,0.0,1.0,1,1.0